-- MySQL Script generated by MySQL Workbench
-- 12/18/16 00:38:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema my_guitar_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_guitar_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_guitar_shop` DEFAULT CHARACTER SET latin1 ;
USE `my_guitar_shop` ;

-- -----------------------------------------------------
-- Table `my_guitar_shop`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`customers` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `email_address` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(60) NOT NULL COMMENT '',
  `first_name` VARCHAR(60) NOT NULL COMMENT '',
  `last_name` VARCHAR(60) NOT NULL COMMENT '',
  `shipping_address_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `billing_address_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`customer_id`)  COMMENT '',
  UNIQUE INDEX `email_address` (`email_address` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`addresses` (
  `address_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `customer_id` INT(11) NOT NULL COMMENT '',
  `line1` VARCHAR(60) NOT NULL COMMENT '',
  `line2` VARCHAR(60) NULL DEFAULT NULL COMMENT '',
  `city` VARCHAR(40) NOT NULL COMMENT '',
  `state` VARCHAR(2) NOT NULL COMMENT '',
  `zip_code` VARCHAR(10) NOT NULL COMMENT '',
  `phone` VARCHAR(12) NOT NULL COMMENT '',
  `disabled` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`address_id`)  COMMENT '',
  INDEX `addresses_fk_customers` (`customer_id` ASC)  COMMENT '',
  CONSTRAINT `addresses_fk_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `my_guitar_shop`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`administrators` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `email_address` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `first_name` VARCHAR(255) NOT NULL COMMENT '',
  `last_name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`admin_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`categories` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `category_name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`category_id`)  COMMENT '',
  UNIQUE INDEX `category_name` (`category_name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`orders` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `customer_id` INT(11) NOT NULL COMMENT '',
  `order_date` DATETIME NOT NULL COMMENT '',
  `ship_amount` DECIMAL(10,2) NOT NULL COMMENT '',
  `tax_amount` DECIMAL(10,2) NOT NULL COMMENT '',
  `ship_date` DATETIME NULL DEFAULT NULL COMMENT '',
  `ship_address_id` INT(11) NOT NULL COMMENT '',
  `card_type` VARCHAR(50) NOT NULL COMMENT '',
  `card_number` CHAR(16) NOT NULL COMMENT '',
  `card_expires` CHAR(7) NOT NULL COMMENT '',
  `billing_address_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`order_id`)  COMMENT '',
  INDEX `orders_fk_customers` (`customer_id` ASC)  COMMENT '',
  CONSTRAINT `orders_fk_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `my_guitar_shop`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`products` (
  `product_id` INT NOT NULL COMMENT '',
  `product_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`order_items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `order_id` INT(11) NOT NULL COMMENT '',
  `product_id` INT(11) NOT NULL COMMENT '',
  `item_price` DECIMAL(10,2) NOT NULL COMMENT '',
  `discount_amount` DECIMAL(10,2) NOT NULL COMMENT '',
  `quantity` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`item_id`)  COMMENT '',
  INDEX `items_fk_orders` (`order_id` ASC)  COMMENT '',
  INDEX `items_fk_products` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `items_fk_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `my_guitar_shop`.`orders` (`order_id`),
  CONSTRAINT `items_fk_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `my_guitar_shop`.`products` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`userInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`userInfo` (
  `user_info_Id` INT NOT NULL COMMENT '',
  `email_address` VARCHAR(45) NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`user_info_Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`products` (
  `product_id` INT NOT NULL COMMENT '',
  `product_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`downloads` (
  `download_id` INT NOT NULL COMMENT '',
  `file_name` VARCHAR(45) NULL COMMENT '',
  `date_time` DATETIME NULL COMMENT '',
  `user_info_userInfo_id` INT NOT NULL COMMENT '',
  `products_product_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`download_id`, `products_product_id`)  COMMENT '',
  INDEX `fk_products_products1_idx` (`products_product_id` ASC)  COMMENT '',
  INDEX `fk_downloads_products1_idx` (`products_product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_downloads_userInfo1`
    FOREIGN KEY (`user_info_userInfo_id`)
    REFERENCES `my_guitar_shop`.`userInfo` (`user_info_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_downloads_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `my_guitar_shop`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
